name: 发布新版本

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 创建发布版本
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行测试
        run: |
          python -m py_compile news_service.py
          echo "语法检查通过"

      - name: 创建发布包
        run: |
          mkdir -p release
          cp news_service.py release/
          cp status_line.sh release/
          cp install.sh release/
          cp requirements.txt release/
          cp README.md release/
          cp LICENSE release/
          cp CHANGELOG.md release/
          
          # 创建压缩包
          cd release
          tar -czf ../claude-code-news-statusline-${GITHUB_REF#refs/tags/}.tar.gz *
          zip -r ../claude-code-news-statusline-${GITHUB_REF#refs/tags/}.zip *

      - name: 生成发布说明
        id: changelog
        run: |
          # 提取当前版本的更新日志
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d' > release_notes.md

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            claude-code-news-statusline-*.tar.gz
            claude-code-news-statusline-*.zip
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 更新安装脚本
        run: |
          # 更新 README 中的版本号
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "发布版本: $VERSION"